/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 19 09:57:58 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MoneyComparatorD_ESTest extends MoneyComparatorD_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn("3A=WnPP;*nXt|U*i{n ", "3A=WnPP;*nXt|U*i{n ").when(driver0).getEmail();
      doReturn(0.0, 0.0, 264.244421710461, (-146.29879867)).when(driver0).getMoney();
      int int0 = moneyComparatorD0.compare(driver0, driver0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(driver0).getEmail();
      doReturn(0.0, 0.0).when(driver0).getMoney();
      Driver driver1 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(driver1).getEmail();
      doReturn(0.0, 0.0).when(driver1).getMoney();
      // Undeclared exception!
      try { 
        moneyComparatorD0.compare(driver0, driver1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("MoneyComparatorD", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(0.0, 264.244421710461, (-3994.91), (-146.29879867)).when(driver0).getMoney();
      int int0 = moneyComparatorD0.compare(driver0, driver0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
      Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
      doReturn(766.143490011, (-4000.95)).when(driver0).getMoney();
      int int0 = moneyComparatorD0.compare(driver0, driver0);
      assertEquals((-1), int0);
  }
}
