package umer;/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 19 09:57:58 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

import java.time.LocalDate;
import java.util.*;
import java.awt.geom.Point2D;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MoneyComparatorD_ESTest extends MoneyComparatorD_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
        Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
        doReturn("3A=WnPP;*nXt|U*i{n ", "3A=WnPP;*nXt|U*i{n ").when(driver0).getEmail();
        doReturn(0.0, 0.0, 264.244421710461, (-146.29879867)).when(driver0).getMoney();
        int int0 = moneyComparatorD0.compare(driver0, driver0);
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
        Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
        doReturn((String) null).when(driver0).getEmail();
        doReturn(0.0, 0.0).when(driver0).getMoney();
        Driver driver1 = mock(Driver.class, new ViolatedAssumptionAnswer());
        doReturn((String) null).when(driver1).getEmail();
        doReturn(0.0, 0.0).when(driver1).getMoney();
        // Undeclared exception!
        try {
            moneyComparatorD0.compare(driver0, driver1);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("umer.MoneyComparatorD", e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
        Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
        doReturn(0.0, 264.244421710461, (-3994.91), (-146.29879867)).when(driver0).getMoney();
        int int0 = moneyComparatorD0.compare(driver0, driver0);
        assertEquals(1, int0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
        Driver driver0 = mock(Driver.class, new ViolatedAssumptionAnswer());
        doReturn(766.143490011, (-4000.95)).when(driver0).getMoney();
        int int0 = moneyComparatorD0.compare(driver0, driver0);
        assertEquals((-1), int0);
    }


    /* Teste manual */
    @Test(timeout = 4000)
    public void test4() throws Throwable {
        MoneyComparatorD moneyComparatorD0 = new MoneyComparatorD();
        Point2D.Double Pontposition = new Point2D.Double(0, 0);
        ArrayList<Trip> trips = new ArrayList<Trip>();
        String queue = "A";
        LocalDate d1 = LocalDate.of(1995, 12, 12);
        String vehicle = "carro";
        Driver cliente1 = new Driver("aaaaf", "Marco", "1234", "Bairro do mal", d1, 0.0, 1.0, false, 0.0, trips, 0, 10.0, 0.0, vehicle, "1", 0.0);
        Driver cliente2 = new Driver("aaaaf", "Miguel", "1234", "Rua da Al", d1, 0.0, 1.0, false, 0.0, trips, 0, 10.0, 0.0, vehicle, "1", 0.0);
        int int0 = moneyComparatorD0.compare(cliente1, cliente2);
        assertEquals(0, int0);
    }

}
