/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 16 17:12:29 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.ChronoLocalDate;
import java.time.chrono.Chronology;
import java.time.chrono.IsoChronology;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.TemporalAccessor;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Locale;
import java.util.TreeSet;
import javafx.application.Application;
import javafx.application.Preloader;
import javafx.beans.property.ReadOnlySetWrapper;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.converter.LocalDateStringConverter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GUI_ESTest extends GUI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "");
      char char0 = '[';
      // Undeclared exception!
      try { 
        gUI0.usersTab((Company) null, "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "N,a,l]kd:]t,&9]t4";
      String string1 = "Top";
      int int0 = 0;
      int int1 = (-1012);
      Period period0 = Period.of(0, 0, (-1012));
      Period period1 = period0.multipliedBy((-1012));
      IsoChronology isoChronology0 = period1.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      gUI0.addClient((String) null, "N,a,l]kd:]t,&9]t4", "Top", "Top", localDate0);
      // Undeclared exception!
      try { 
        gUI0.errorLabel("<$,uOnF/");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GUI gUI0 = new GUI();
      UMeR uMeR0 = new UMeR();
      String string0 = "'N.IhJH6";
      // Undeclared exception!
      try { 
        gUI0.printCompany((Company) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GUI gUI0 = new GUI();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "q/Oe_ji+u1TH)Cg";
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike((String) null, (-2848.6722), point2D_Double0, "xn1yY}!=yzFqaI6");
      Bike bike1 = bike0.clone();
      bike1.getQueueInfo();
      ArrayList<Trip> arrayList0 = bike1.getTrips();
      gUI0.printTripsByDate("q/Oe_ji+u1TH)Cg", arrayList0);
      stringArray0[2] = "x%k1+!$}|V;s-K1/";
      stringArray0[3] = "`@lLOF77?JYY0";
      stringArray0[4] = "Informa\u00E7\u00E3o Pessoal";
      stringArray0[5] = "(S1Y(";
      stringArray0[6] = "2nHGhB_`VN&dq";
      // Undeclared exception!
      try { 
        gUI0.Main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GUI gUI0 = new GUI();
      String[] stringArray0 = new String[5];
      stringArray0[0] = "N\u00FAmero de viagens : ";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "Data de Anivers\u00E1rio";
      stringArray0[4] = "B^%BY";
      // Undeclared exception!
      try { 
        gUI0.Main(stringArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      LocalDate localDate0 = null;
      gUI0.addClient("", "", "", "Yn%kl[SK8:zz", (LocalDate) null);
      Company company0 = new Company("^;G^", "So2?m5\"l5");
      gUI0.printCompany(company0);
      // Undeclared exception!
      try { 
        gUI0.loadMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javafx.scene.Node
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = null;
      // Undeclared exception!
      try { 
        gUI0.passwordRegisterBox((String) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.errorLabel("\nDura\u00E7\u00E3o real : ");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.vehicleClassBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.addCompany((String) null, "uN>a3G");
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.addCompany("", "");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.textRegisterBox("@^,'");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GUI gUI0 = new GUI();
      TreeSet<Driver> treeSet0 = new TreeSet<Driver>();
      gUI0.printTopRating(treeSet0);
      String string0 = ")";
      // Undeclared exception!
      try { 
        gUI0.textRegisterBox(")");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.getParameters();
      TreeSet<Driver> treeSet0 = null;
      // Undeclared exception!
      try { 
        gUI0.printTopRating((TreeSet<Driver>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.adminMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GUI gUI0 = new GUI();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(786L);
      gUI0.addClient("", "", "", "", localDate0);
      // Undeclared exception!
      try { 
        gUI0.adminMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.saveData();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GUI gUI0 = new GUI();
      Point2D.Double point2D_Double0 = new Point2D.Double();
      // Undeclared exception!
      try { 
        gUI0.addVehicle("\nTempo real at\u00E9 ao cliente : ", "\nTempo real at\u00E9 ao cliente : ", "\nTempo real at\u00E9 ao cliente : ", point2D_Double0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.moneyGeneratedBetweenBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      // Undeclared exception!
      try { 
        gUI0.positionBox("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.HBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.printTime(2798.439890381);
      Period period0 = Period.of(0, 0, 5);
      Period period1 = period0.minusMonths(0);
      IsoChronology isoChronology0 = period1.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      // Undeclared exception!
      try { 
        gUI0.moneyGeneratedBetween("2798h:26m:24s", localDate0, localDate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GUI gUI0 = new GUI();
      Company company0 = new Company("^W@=|$4I-,uL3,azJ", "Ul(<`]@qG>:c");
      // Undeclared exception!
      try { 
        gUI0.vehiclesTab(company0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      GUI gUI0 = new GUI();
      GUI gUI1 = new GUI();
      String string0 = "WmsG+>C";
      // Undeclared exception!
      try { 
        gUI1.companyMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      GUI gUI0 = new GUI();
      HashMap<Van, Application> hashMap0 = new HashMap<Van, Application>();
      gUI0.printIdentifier(hashMap0);
      // Undeclared exception!
      try { 
        gUI0.backButton();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Button
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      GUI gUI0 = new GUI();
      StageStyle stageStyle0 = StageStyle.UNDECORATED;
      // Undeclared exception!
      try { 
        gUI0.loadMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javafx.scene.Node
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.printTime((-10.0));
      HashMap<Integer, Company> hashMap0 = new HashMap<Integer, Company>();
      Company company0 = new Company("X%6d", "99,M`vAJ");
      Company company1 = new Company(company0);
      hashMap0.put((Integer) null, company1);
      gUI0.printIdentifier(hashMap0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.clientSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.companySignup();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.driverSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.companyRegisterBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      GUI gUI0 = new GUI();
      Company company0 = new Company("wu", (String) null);
      Company company1 = company0.clone();
      company1.getDates();
      company1.pickDriver();
      company0.getDrivers();
      company1.getTrips();
      // Undeclared exception!
      try { 
        gUI0.usersTab(company1, "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.stop();
      gUI0.printAdminInfo();
      // Undeclared exception!
      try { 
        gUI0.companySignup();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.printDistance(1049.251);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      GUI gUI0 = new GUI();
      GUI gUI1 = new GUI();
      gUI1.printTime(100.0);
      // Undeclared exception!
      try { 
        gUI1.backButton();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Button
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.clientMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      GUI gUI0 = new GUI();
      TreeSet<Client> treeSet0 = new TreeSet<Client>();
      gUI0.printTopMoney(treeSet0);
      String string0 = "N\u00FAmero de clientes em fila de espera - ";
      String string1 = "";
      // Undeclared exception!
      try { 
        gUI0.userHeaderBox(treeSet0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      GUI gUI0 = new GUI();
      Boolean boolean0 = Boolean.FALSE;
      // Undeclared exception!
      try { 
        gUI0.userHeaderBox(boolean0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GUI gUI0 = new GUI();
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Helicopter helicopter0 = new Helicopter("", 50.0, point2D_Double0, "images/driver_small.png");
      Helicopter helicopter1 = new Helicopter(helicopter0);
      gUI0.printVehicle(helicopter1);
      // Undeclared exception!
      try { 
        gUI0.companyRegisterBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      GUI gUI0 = new GUI();
      Company company0 = new Company("Muito Bom", "Ia:C,e*Ya?XdZRiK%V");
      // Undeclared exception!
      try { 
        gUI0.usersTab(company0, "Muito Bom");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      GUI gUI0 = new GUI();
      LocalDate localDate0 = MockLocalDate.now();
      gUI0.addClient("\n---Condutores \n", "\n---Condutores \n", "\n---Condutores \n", "Empresa j\u00E1 existe", localDate0);
      gUI0.printMoney((-2029.273917405491));
      // Undeclared exception!
      try { 
        gUI0.driverSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.successLabel("=@q' <4Rs$nJ!");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      GUI gUI0 = new GUI();
      Company company0 = new Company("", "");
      Company company1 = company0.clone();
      Company company2 = new Company(company1);
      gUI0.printCompany(company2);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      GUI gUI0 = new GUI();
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        gUI0.infoTab(object0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "Tipo : ";
      // Undeclared exception!
      try { 
        gUI0.doneRegisterButton();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Button
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.datesBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.ComboBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      // Undeclared exception!
      try { 
        gUI0.vehicleSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "L";
      // Undeclared exception!
      try { 
        gUI0.driverMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.vehicleConditionBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "images/driver_small.png";
      LocalDate localDate0 = MockLocalDate.now();
      Client client0 = new Client("\nVe\u00EDculo : ", "images/driver_small.png", "ul}W1LB4s\"F+=MLL", "ul}W1LB4s\"F+=MLL", localDate0);
      client0.setPassword("\nPassword : ");
      client0.getPosition();
      client0.setPassword("ul}W1LB4s\"F+=MLL");
      // Undeclared exception!
      try { 
        gUI0.infoTab(client0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.doneRegisterButton();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Button
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      GUI gUI0 = new GUI();
      gUI0.addCompany("^^Cm", "^^Cm");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      gUI0.printTripsByDate("Viagem de (", arrayList0);
      // Undeclared exception!
      try { 
        gUI0.datesBox();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.ComboBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.vehicleSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.driverMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      GUI gUI0 = new GUI();
      TreeSet<Driver> treeSet0 = new TreeSet<Driver>();
      gUI0.printTD(treeSet0);
      // Undeclared exception!
      try { 
        gUI0.companiesTab();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.loginMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.clientSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      GUI gUI0 = new GUI();
      TreeSet<Driver> treeSet0 = new TreeSet<Driver>();
      gUI0.printTD(treeSet0);
      String string0 = "P)Q9~FOPU";
      String string1 = null;
      String string2 = "Registar";
      DateTimeFormatter dateTimeFormatter0 = DateTimeFormatter.ISO_OFFSET_DATE_TIME;
      LocalDateStringConverter localDateStringConverter0 = new LocalDateStringConverter(dateTimeFormatter0, dateTimeFormatter0);
      // Undeclared exception!
      try { 
        localDateStringConverter0.fromString("Matr\u00EDcula: ");
        fail("Expecting exception: DateTimeParseException");
      
      } catch(DateTimeParseException e) {
         //
         // Text 'Matr\u00EDcula:' could not be parsed at index 0
         //
         verifyException("java.time.format.DateTimeFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.companiesTab();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.loginMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.clientSignupMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      String string1 = ")\\=8<+KC<@Df!d";
      String string2 = "\nMorada: ";
      Clock clock0 = MockClock.systemDefaultZone();
      LocalDate localDate0 = MockLocalDate.now(clock0);
      Client client0 = new Client("", ")=8<+KC<@Df!d", "\nMorada: ", "", localDate0);
      Point2D.Double point2D_Double0 = new Point2D.Double(1046.2385449, 2106.9);
      point2D_Double0.clone();
      gUI0.newTrip(client0, ")=8<+KC<@Df!d", point2D_Double0, point2D_Double0);
      // Undeclared exception!
      try { 
        gUI0.printTD((TreeSet<Driver>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "0@FezF";
      gUI0.loginCheck("0@FezF", "0@FezF");
      // Undeclared exception!
      try { 
        gUI0.successLabel("0@FezF");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "d$YCu6";
      Client client0 = null;
      try {
        client0 = new Client((Client) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Client", e);
      }
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "Email";
      String string1 = "RVRZX;G'2.o&gMZ&=Y";
      double double0 = 0.0;
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Bike bike0 = new Bike("RVRZX;G'2.o&gMZ&=Y", 0.0, point2D_Double0, "RVRZX;G'2.o&gMZ&=Y");
      Bike bike1 = bike0.clone();
      Point2D.Double point2D_Double1 = bike1.getPosition();
      // Undeclared exception!
      try { 
        gUI0.addVehicle("Email", "RVRZX;G'2.o&gMZ&=Y", "RVRZX;G'2.o&gMZ&=Y", point2D_Double1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      GUI gUI0 = new GUI();
      int int0 = (-2443);
      HashMap<Trip, TextField> hashMap0 = null;
      try {
        hashMap0 = new HashMap<Trip, TextField>((-2443));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal initial capacity: -2443
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      GUI gUI0 = new GUI();
      // Undeclared exception!
      try { 
        gUI0.companySignup();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "";
      String string1 = "zAX/T";
      String string2 = null;
      String string3 = "";
      int int0 = 1355;
      // Undeclared exception!
      try { 
        MockLocalDate.ofYearDay(1355, 0);
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for DayOfYear (valid values 1 - 365/366): 0
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      GUI gUI0 = new GUI();
      GUI gUI1 = new GUI();
      // Undeclared exception!
      try { 
        gUI1.companyMenu();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.layout.VBox
         //
         verifyException("GUI", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      GUI gUI0 = new GUI();
      String string0 = "dx\\k9}V_c";
      // Undeclared exception!
      try { 
        gUI0.errorLabel("dxk9}V_c");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class javafx.scene.control.Label
         //
         verifyException("GUI", e);
      }
  }
}
