/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 19 09:57:37 GMT 2018
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.geom.Point2D;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.IsoChronology;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Driver_ESTest extends Driver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("bd`wyxIq]y$T~?47", "i73DekMHzpIC", "", "bd`wyxIq]y$T~?47", localDate0, (-1055.396116), "");
      driver0.addRating(2);
      assertEquals(40.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-2206L));
      Driver driver0 = new Driver("", "8h}z+BUcm0C(t", "\nN\u00FAmero de classifica\u00E7\u00F5es : ", "z~AnRp(lfv5?F!K9zs.", localDate0, (-2206L), "]a!s{GBlHz");
      Point2D.Double point2D_Double0 = new Point2D.Double(3529, 0.0);
      Point2D.Double point2D_Double1 = new Point2D.Double();
      Trip trip0 = new Trip(3529, point2D_Double0, point2D_Double0, (Double) 0.0, (Double) point2D_Double0.y, localDate0, (String) null, "dC3s$UD", "]a!s{GBlHz", 3529, (-2206L), point2D_Double1, 4.0, (-1230.6507577229), 0.0);
      driver0.addTrip(trip0);
      assertEquals(3529.0, driver0.getTotalDistance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nPremium : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("gVR@zW*;k-mY5;Q-<", "", "", "<w~,~Pab%RA", localDate0, 2537.83319943493, (-1093.74541371582), boolean0, 0.0, arrayList0, 4582, 2537.83319943493, 928.05254176069, "\nPremium : ", "h:", (-1272.0));
      driver0.isAvailable();
      assertEquals((-1272.0), driver0.getDeviation(), 0.01);
      assertEquals((-1093.74541371582), driver0.getRating(), 0.01);
      assertEquals("h:", driver0.getCompany());
      assertEquals(4582, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals("\nPremium : ", driver0.getVehicle());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", localDate0, 0L, "!(LAG5#!@vrV_@H}>>");
      driver0.getVehicle();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>(669);
      Driver driver0 = new Driver("\nPosi\u00E7\u00E3o inicial do taxi : [", "\nPosi\u00E7\u00E3o inicial do taxi : [", "", "\nPosi\u00E7\u00E3o inicial do taxi : [", localDate0, (-415.96394), 0.0, boolean0, 0.0, arrayList0, 669, 669, (-415.96394), "zYVGP%3!c\"tX-", "N\u00E3o classificado", (-415.96394));
      String string0 = driver0.getVehicle();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals((-415.96394), driver0.getDeviation(), 0.01);
      assertEquals("N\u00E3o classificado", driver0.getCompany());
      assertEquals("zYVGP%3!c\"tX-", string0);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(669, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      Double double0 = driver0.getTimeCompliance();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(1840.0, (double)double0, 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("bd`wyxIq]y$T~?47", "bd`wyxIq]y$T~?47", "bd`wyxIq]y$T~?47", (String) null, localDate0, (-1L), "bd`wyxIq]y$T~?47");
      Double double0 = driver0.getTimeCompliance();
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals((-1.0), (double)double0, 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(3451L);
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("dPIt_", "%VTj%$4x<[6H~'Oi\u0001", "", "", localDate0, 0.0, 0.0, boolean0, (-1279.551), arrayList0, 893, (-1279.551), 3451L, (String) null, "dPIt_", 0.0);
      driver0.addRating(893);
      driver0.getRating();
      assertEquals(894, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      driver0.addRating((-3765));
      driver0.getRating();
      assertEquals((-3769), driver0.getExp());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1009L));
      Driver driver0 = new Driver("\nData de nascimento : ", "\nData de nascimento : ", "\nData de nascimento : ", (String) null, localDate0, (-1009L), (String) null);
      int int0 = driver0.getNumberOfReviews();
      assertEquals((-1009.0), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Driver driver0 = new Driver("", "7w!~dxd~", (String) null, (String) null, localDate0, 0.0, "oSMn");
      driver0.setExp(3);
      int int0 = driver0.getExp();
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Driver driver0 = new Driver("", "7w!~dxd~", "7w!~dxd~", "7w!~dxd~", localDate0, 0.0, "7w!~dxd~");
      driver0.addRating((-250));
      int int0 = driver0.getExp();
      assertEquals(1, driver0.getNumberOfReviews());
      assertEquals((-254), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Boolean boolean0 = Boolean.valueOf("/y`Z'bZghH`");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("/y`Z'bZghH`", "/y`Z'bZghH`", "/y`Z'bZghH`", "HdD.1uqD8`P]bL", localDate0, 1.0, 3329.641764, boolean0, 1.0, arrayList0, (-2214), 3329.641764, 1.0, "/y`Z'bZghH`", "HdD.1uqD8`P]bL", (-2214));
      double double0 = driver0.getDeviation();
      assertEquals(1.0, driver0.getTimeCompliance(), 0.01);
      assertEquals("HdD.1uqD8`P]bL", driver0.getCompany());
      assertEquals((-2214.0), double0, 0.01);
      assertEquals("/y`Z'bZghH`", driver0.getVehicle());
      assertEquals((-2214), driver0.getNumberOfReviews());
      assertEquals(3329.641764, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1668L);
      Driver driver0 = new Driver("", (String) null, (String) null, "gq", localDate0, 1952.34634, "gq");
      String string0 = driver0.getCompany();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals("gq", string0);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(1952.34634, driver0.getTimeCompliance(), 0.01);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(193L);
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, 193L, (-1.0), boolean0, (-1.0), arrayList0, (-65), (-1.0), (-2469.951), "", "", 2.0);
      driver0.getCompany();
      assertEquals(2.0, driver0.getDeviation(), 0.01);
      assertEquals((-1.0), driver0.getRating(), 0.01);
      assertEquals((-1.0), driver0.getTimeCompliance(), 0.01);
      assertEquals((-65), driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("7x!/u7J;H[F", "7x!/u7J;H[F", "7x!/u7J;H[F", "7x!/u7J;H[F", localDate0, (-2881.34423), "7x!/u7J;H[F");
      driver0.equals(driver0);
      assertEquals((-2881.34423), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Period period0 = Period.ofWeeks(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("bd`wyxIq]y$T~?47", "i73DekMHzpIC", "", "bd`wyxIq]y$T~?47", localDate0, (-1055.396116), "");
      Boolean boolean0 = Boolean.FALSE;
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver1 = new Driver("", "\nDisponibilidade : ", "U~q*O1%C=Fym", "\nDinheiro gasto/ganho : ", localDate0, 0.0, 0, boolean0, 0, arrayList0, 0, 0.0, 372.057, "U~q*O1%C=Fym", "U`JJ{CpZ|t]>;l-L", 2.0);
      boolean boolean1 = driver0.equals(driver1);
      assertEquals((-1055.396116), driver0.getTimeCompliance(), 0.01);
      assertEquals(2.0, driver1.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertFalse(boolean1);
      assertEquals("U`JJ{CpZ|t]>;l-L", driver1.getCompany());
      assertEquals("U~q*O1%C=Fym", driver1.getVehicle());
      assertEquals("", driver0.getCompany());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver1.getRating(), 0.01);
      assertEquals(0, driver1.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver1.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Period period0 = Period.ofYears(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Boolean boolean0 = Boolean.valueOf("");
      Driver driver0 = new Driver("", "Viagem de (", "", "kH`Eq,I}B", localDate0, 3272.519826, "");
      ArrayList<Trip> arrayList0 = driver0.getTrips();
      Driver driver1 = new Driver("kH`Eq,I}B", (String) null, "kH`Eq,I}B", "", localDate0, 3272.519826, 0.0, boolean0, 0.0, arrayList0, (-872), 3272.519826, 0.0, "kH`Eq,I}B", (String) null, 1010.48);
      Driver driver2 = driver1.clone();
      double double0 = driver2.getDeviation();
      assertEquals(1010.48, double0, 0.01);
      assertEquals(0.0, driver1.getTimeCompliance(), 0.01);
      assertEquals("", driver0.getCompany());
      assertEquals(0, driver2.getExp());
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver1.getRating(), 0.01);
      assertEquals((-872), driver2.getNumberOfReviews());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(3272.519826, driver0.getTimeCompliance(), 0.01);
      assertEquals("kH`Eq,I}B", driver2.getVehicle());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals((-872), driver1.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      driver0.setMoney(1840L);
      Driver driver1 = driver0.clone();
      assertEquals(1840.0, driver0.getTimeCompliance(), 0.01);
      assertEquals(0, driver1.getExp());
      assertTrue(driver1.isAvailable());
      assertEquals(1840.0, driver1.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(60L);
      Driver driver0 = new Driver("", "", "umer.Driver", "b", localDate0, 0.0, "FxZEuCe/cf%$(S%");
      driver0.addRating(1207);
      driver0.clone();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(60L);
      Driver driver0 = new Driver("", "", "umer.Driver", "b", localDate0, 0.0, "FxZEuCe/cf%$(S%");
      Point2D.Double point2D_Double0 = new Point2D.Double();
      Trip trip0 = new Trip(0, point2D_Double0, point2D_Double0, (Double) 0.0, (Double) point2D_Double0.x, localDate0, "l{L()bv,ZpgRY4Z", "c\"QHNFf@*ptB!Q\"v", "", 0, 0.0, point2D_Double0, 60L, 0.0, (-1489.692));
      driver0.addTrip(trip0);
      driver0.clone();
      assertEquals(1489.692, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-3875L));
      Boolean boolean0 = Boolean.valueOf(true);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("E0(@Yr", "E0(@Yr", "E0(@Yr", "E0(@Yr", localDate0, (-504.5478589020717), (-1879.1958508212), boolean0, 0.0, arrayList0, 0, (-3875L), 0.0, "E0(@Yr", "E0(@Yr", (-3842.573239));
      Driver driver1 = driver0.clone();
      assertEquals(0, driver1.getNumberOfReviews());
      assertEquals((-1879.1958508212), driver0.getRating(), 0.01);
      assertEquals((-3842.573239), driver1.getDeviation(), 0.01);
      assertEquals((-3842.573239), driver0.getDeviation(), 0.01);
      assertEquals((-1879.1958508212), driver1.getRating(), 0.01);
      assertTrue(driver1.isAvailable());
      assertEquals(0, driver1.getExp());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Month month0 = Month.MAY;
      LocalDate localDate0 = MockLocalDate.of((-742), month0, 1);
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "]\nTempo previsto at\u00E9 ao cliente : ", "", localDate0, (-742), "\nEmail cliente : ");
      // Undeclared exception!
      try { 
        driver0.setAvailability((Boolean) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      arrayList0.add((Trip) null);
      Driver driver0 = new Driver("", "", "", "", localDate0, (-1569.82891435507), (-1569.82891435507), boolean0, (-1569.82891435507), arrayList0, (-378), (-1569.82891435507), (-378), "", "s", (-378));
      // Undeclared exception!
      try { 
        driver0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver("Uy[~oc@O'$g$", "Uy[~oc@O'$g$", "Uy[~oc@O'$g$", "2A/cq?d}ED'sR}g", (LocalDate) null, (-2523.554), "Uy[~oc@O'$g$");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Boolean boolean0 = new Boolean("");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = null;
      try {
        driver0 = new Driver("", "", "", "", (LocalDate) null, (-909.8385968725308), 3600.0, boolean0, 2.0, arrayList0, 0, 1611.0720767, 756.5471733339, "", "\nData de nascimento : ", (-1089.814446));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver((Driver) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.Driver", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>(669);
      Driver driver0 = new Driver("\nPosi\u00E7\u00E3o inicial do taxi : [", "\nPosi\u00E7\u00E3o inicial do taxi : [", "", "\nPosi\u00E7\u00E3o inicial do taxi : [", localDate0, (-415.96394), 0.0, boolean0, 0.0, arrayList0, 669, 669, (-415.96394), "zYVGP%3!c\"tX-", "N\u00E3o classificado", (-415.96394));
      Double double0 = driver0.getRating();
      assertEquals(0.0, (double)double0, 0.01);
      assertEquals(669, driver0.getNumberOfReviews());
      assertEquals((-415.96394), driver0.getDeviation(), 0.01);
      assertEquals("zYVGP%3!c\"tX-", driver0.getVehicle());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals("N\u00E3o classificado", driver0.getCompany());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(60L);
      Driver driver0 = new Driver("\n", "\n", "", "\n", localDate0, (-5220.7439740071), "\n");
      double double0 = driver0.getDeviation();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals("\n", driver0.getCompany());
      assertEquals(0.0, double0, 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-5220.7439740071), driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nPremium : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("gVR@zW*;k-mY5;Q-<", "", "", "<w~,~Pab%RA", localDate0, 2537.83319943493, (-1093.74541371582), boolean0, 0.0, arrayList0, 4582, 2537.83319943493, 928.05254176069, "\nPremium : ", "h:", (-1272.0));
      Driver driver1 = new Driver(driver0);
      assertEquals("h:", driver1.getCompany());
      assertEquals(0, driver1.getExp());
      assertEquals(4582, driver1.getNumberOfReviews());
      assertEquals(4582, driver0.getNumberOfReviews());
      assertEquals("\nPremium : ", driver1.getVehicle());
      assertEquals((-1272.0), driver0.getDeviation(), 0.01);
      assertEquals((-1093.74541371582), driver1.getRating(), 0.01);
      assertEquals((-1093.74541371582), driver0.getRating(), 0.01);
      assertEquals((-1272.0), driver1.getDeviation(), 0.01);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-1009L));
      Driver driver0 = new Driver("\nData de nascimento : ", "\nData de nascimento : ", "\nData de nascimento : ", (String) null, localDate0, (-1009L), (String) null);
      String string0 = driver0.getCompany();
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertNull(string0);
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-1009.0), driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nPremium : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("gVR@zW*;k-mY5;Q-<", "", "", "<w~,~Pab%RA", localDate0, 2537.83319943493, (-1093.74541371582), boolean0, 0.0, arrayList0, 4582, 2537.83319943493, 928.05254176069, "\nPremium : ", "h:", (-1272.0));
      int int0 = driver0.getNumberOfReviews();
      assertEquals("h:", driver0.getCompany());
      assertEquals(4582, int0);
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
      assertEquals((-1272.0), driver0.getDeviation(), 0.01);
      assertEquals("\nPremium : ", driver0.getVehicle());
      assertEquals((-1093.74541371582), driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      Driver driver0 = new Driver("!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", "!(LAG5#!@vrV_@H}>>", localDate0, 0L, "!(LAG5#!@vrV_@H}>>");
      int int0 = driver0.getExp();
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, int0);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertTrue(driver0.isAvailable());
      assertEquals(0.0, driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Boolean boolean0 = new Boolean("\nPremium : ");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("gVR@zW*;k-mY5;Q-<", "", "", "<w~,~Pab%RA", localDate0, 2537.83319943493, (-1093.74541371582), boolean0, 0.0, arrayList0, 4582, 2537.83319943493, 928.05254176069, "\nPremium : ", "h:", (-1272.0));
      Double double0 = driver0.getTimeCompliance();
      assertEquals((-1093.74541371582), driver0.getRating(), 0.01);
      assertEquals("\nPremium : ", driver0.getVehicle());
      assertEquals(4582, driver0.getNumberOfReviews());
      assertEquals("h:", driver0.getCompany());
      assertEquals(0.0, (double)double0, 0.01);
      assertEquals((-1272.0), driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(193L);
      Boolean boolean0 = Boolean.valueOf(false);
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("", "", "", "", localDate0, 193L, (-1.0), boolean0, (-1.0), arrayList0, (-65), (-1.0), (-2469.951), "", "", 2.0);
      driver0.getVehicle();
      assertEquals((-65), driver0.getNumberOfReviews());
      assertEquals((-1.0), driver0.getTimeCompliance(), 0.01);
      assertEquals((-1.0), driver0.getRating(), 0.01);
      assertEquals(2.0, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      driver0.addRating((-3765));
      driver0.clone();
      assertEquals(1, driver0.getNumberOfReviews());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      // Undeclared exception!
      try { 
        driver0.addTrip((Trip) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("umer.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Month month0 = Month.MAY;
      LocalDate localDate0 = MockLocalDate.of((-742), month0, 1);
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "]\nTempo previsto at\u00E9 ao cliente : ", "", localDate0, (-742), "\nEmail cliente : ");
      Boolean boolean0 = driver0.isAvailable();
      assertTrue(boolean0);
      
      driver0.setAvailability(boolean0);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals("\nEmail cliente : ", driver0.getCompany());
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertEquals((-742.0), driver0.getTimeCompliance(), 0.01);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Period period0 = Period.of(5443, 5443, 1387);
      IsoChronology isoChronology0 = period0.getChronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0, (ZoneId) zoneOffset0);
      Driver driver0 = new Driver((String) null, (String) null, (String) null, (String) null, localDate0, 1387, (String) null);
      // Undeclared exception!
      try { 
        driver0.equals(driver0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      driver0.setdeviation(1327.6659117);
      assertEquals(1327.6659117, driver0.getDeviation(), 0.01);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Trip trip0 = new Trip();
      LocalDate localDate0 = trip0.getDate();
      Boolean boolean0 = Boolean.valueOf("/y`Z'bZghH`");
      ArrayList<Trip> arrayList0 = new ArrayList<Trip>();
      Driver driver0 = new Driver("/y`Z'bZghH`", "/y`Z'bZghH`", "/y`Z'bZghH`", "HdD.1uqD8`P]bL", localDate0, 1.0, 3329.641764, boolean0, 1.0, arrayList0, (-2214), 3329.641764, 1.0, "/y`Z'bZghH`", "HdD.1uqD8`P]bL", (-2214));
      assertEquals("/y`Z'bZghH`", driver0.getVehicle());
      
      driver0.setVehicle("rq\"n\"d 0)_N,sN");
      assertEquals("HdD.1uqD8`P]bL", driver0.getCompany());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Period period0 = Period.ofYears(0);
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      Driver driver0 = new Driver("", "Viagem de (", "", "kH`Eq,I}B", localDate0, 3272.519826, "");
      driver0.setRating((-872));
      assertEquals((-872.0), driver0.getRating(), 0.01);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Month month0 = Month.MAY;
      LocalDate localDate0 = MockLocalDate.of((-742), month0, 1);
      Driver driver0 = new Driver("\nDisponibilidade : ", "\nDisponibilidade : ", "]\nTempo previsto at\u00E9 ao cliente : ", "", localDate0, (-742), "\nEmail cliente : ");
      driver0.setNumberOfReviews((-1));
      int int0 = driver0.getNumberOfReviews();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Driver driver0 = null;
      try {
        driver0 = new Driver();
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for MonthOfYear (valid values 1 - 12): 0
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.ofEpochDay(1840L);
      Driver driver0 = new Driver(") ---> (", "umer.Driver", "l$8>(q\"47_>}", "?+/RU*HF1T5?_U", localDate0, 1840L, (String) null);
      String string0 = driver0.toString();
      assertEquals("umer.Driver \nUtilizador - umer.Driver\neMail : ) ---> (\nPassword : l$8>(q\"47_>}\nMorada : ?+/RU*HF1T5?_U\nData de nascimento : 1975-01-15\nDist\u00E2ncia Total : 0.0\nDinheiro gasto/ganho : 0.0\nN\u00FAmero de viagens :0\nDisponibilidade : true\nClassifica\u00E7\u00E3o : 0.0\nGrau de cumprimento : 1840.0\nN\u00FAmero de classifica\u00E7\u00F5es : 0\nVe\u00EDculo : null\nDesvio total : 0.0\n", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      LocalDate localDate0 = MockLocalDate.now();
      Driver driver0 = new Driver("bd`wyxIq]y$T~?47", "bd`wyxIq]y$T~?47", "bd`wyxIq]y$T~?47", (String) null, localDate0, (-1L), "bd`wyxIq]y$T~?47");
      driver0.setTimeCompliance((-1L));
      assertEquals(0.0, driver0.getRating(), 0.01);
      assertEquals((-1.0), driver0.getTimeCompliance(), 0.01);
      assertEquals(0.0, driver0.getDeviation(), 0.01);
      assertEquals(0, driver0.getNumberOfReviews());
      assertTrue(driver0.isAvailable());
  }
}
